apiVersion: v1
kind: Service
metadata:
  name: ms-jave-micro-service
  namespace: javeriana
spec:
  type: LoadBalancer
  selector:
    app: ms-jave-micro
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
