name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    
    runs-on: profe

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64
        
    - name: Run the Maven verify phase
      run: mvn package -DskipTests
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ms-jave-micro:${{ github.run_number }}
 
    - name: Push the Docker image
      run: | 
        docker tag ms-jave-micro:${{ github.run_number }} mauron/ms-jave-micro:${{ github.run_number }}
        docker push mauron/ms-jave-micro:${{ github.run_number }}
  
  deploy:

    runs-on: profe
    
    steps:

    - name: replace
      run: sed -i 's/TAG/${{ github.run_number }}/g' docker-compose.yaml

    - name: run docker-compose
      run: docker compose up -d
    